### PR TITLE
Use public API for modelClass and getJsonSchema

### PR DESCRIPTION
**Pull request by jordaaash**
Avoids breaking if private props change as implementation details.

### CODE REVIEW

**Review by snlamm — CHANGES_REQUESTED** [review]
Thanks for fix! I think it might be `this.modelClass().getJsonSchema()`. If you'd like to change it, please do so and I'll merge it in.

**Comment by jordaaash** [comment]
Hah! You're right, I'm an idiot.

**Comment by jordaaash** [comment]
I'll squash them if it helps.

**Comment by snlamm** [comment]
thanks that would be good

**Comment by jordaaash** [comment]
Cool, did a rebase fixup.

**Review by snlamm — APPROVED** [review]

**Pull request merged**
